/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import db.SessionManager;
import db.UserDAO;
import db.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class addDebt extends javax.swing.JFrame {

    /**
     * Creates new form addDebt
     */
    public addDebt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountTextField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dueDateTextField = new javax.swing.JTextArea();
        ayosButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        creditorUsernameTextField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("GET MONEY");

        amountTextField.setColumns(20);
        amountTextField.setRows(5);
        jScrollPane1.setViewportView(amountTextField);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("WHAT DATE");

        dueDateTextField.setColumns(20);
        dueDateTextField.setRows(5);
        jScrollPane2.setViewportView(dueDateTextField);

        ayosButton.setText("Ayos!");
        ayosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayosButtonActionPerformed(evt);
            }
        });

        creditorUsernameTextField.setColumns(20);
        creditorUsernameTextField.setRows(5);
        jScrollPane3.setViewportView(creditorUsernameTextField);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("WHICH MF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(ayosButton)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ayosButton)
                        .addGap(41, 41, 41)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

private void ayosButtonActionPerformed(java.awt.event.ActionEvent evt) { 
// Get the amount owed from the user input
    String amountText = amountTextField.getText().trim();
    if (amountText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Amount owed is required.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    double amount;
    try {
        amount = Double.parseDouble(amountText);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Please enter a valid amount.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the creditor's username
    String creditorUsername = creditorUsernameTextField.getText().trim();
    if (creditorUsername.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Creditor username is required.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Check if creditor exists
    int creditorId = 0;
    try {
        creditorId = UserDAO.getCreditorIdFromUsername(creditorUsername);  // Check if creditor exists
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Creditor not found: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the due date
    String dueDateText = dueDateTextField.getText().trim();
    java.sql.Date dateDue = null;
    
    if (!dueDateText.isEmpty()) {
        try {
            // If user input is provided, parse the date
            dateDue = java.sql.Date.valueOf(dueDateText);
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(null, 
                "Invalid date format. Please use yyyy-mm-dd.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    } else {
        // If no due date is provided, set it to 3 days after the current date
        java.util.Calendar calendar = java.util.Calendar.getInstance();
        calendar.add(java.util.Calendar.DATE, 3);  // Add 3 days to the current date
        dateDue = new java.sql.Date(calendar.getTimeInMillis());  // Set the date
    }

    // Get the debtor's ID from the session
    int debtorId = 1; //SessionManager.getInstance().getUserId(); hardcode for testing

    // SQL query to insert debt
    String insertDebtQuery = "INSERT INTO debts (debtor_id, creditor_id, amount, date_issued, date_due, is_paid) "
                            + "VALUES (?, ?, ?, CURDATE(), ?, ?)";

    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(insertDebtQuery)) {

        stmt.setInt(1, debtorId);   // Set debtor_id
        stmt.setInt(2, creditorId); // Set creditor_id
        stmt.setDouble(3, amount);  // Set amount owed
        stmt.setDate(4, dateDue);   // Set due date (either provided or calculated)
        stmt.setBoolean(5, false);  // Set is_paid to false by default

        int rowsAffected = stmt.executeUpdate();  // Execute insert

        if (rowsAffected > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, 
                "Debt record added successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, 
                "Failed to add debt record.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Error while saving debt record: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}    

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea dueDateTextField; // duedate
    private javax.swing.JTextArea amountTextField; // amount owed
    private javax.swing.JTextArea creditorUsernameTextField; // creditors username
    private javax.swing.JButton ayosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration                   
}